### ISSUE TITLE
Create an explanatory Jupyter notebook

### ISSUE THREAD

**Issue by MridulS** [networkx/outreachy#8]
[Everyone can do this task. There is no need to claim/assign this issue]

Once you have [installed networkx](https://github.com/networkx/outreachy/issues/2) and are [comfortable with the NetworkX API](https://github.com/networkx/outreachy/issues/5) the next task is to create a Jupyter Notebook and submit that notebook to this repository. The Outreachy project is about creating Pedagogical Interactive Notebooks and this task will help you with getting familiar with the Jupyter notebook interface.

The applicant needs to submit a Jupyter notebook (`.ipynb` file) which does the following operations:

- Create a [random erdos-renyi graph](https://networkx.org/documentation/latest/reference/generated/networkx.generators.random_graphs.erdos_renyi_graph.html#erdos-renyi-graph) with 100 nodes and a edge probability of 0.3
- Plot the [degree_centrality](https://networkx.org/documentation/latest/reference/algorithms/generated/networkx.algorithms.bipartite.centrality.degree_centrality.html) distribution (a histogram of the degree centrality values).
- Change the edge probability of the erdos-reyni graph to 0.6 and plot the degree centrality distribution again.
- Infer the changes in the plots, why does the degree centrality distribution change. Create a markdown cell in the jupyter notebook and write what you can infer from the plots. 
- Create a random [barabasi_albert_graph](https://networkx.org/documentation/latest/reference/generated/networkx.generators.random_graphs.barabasi_albert_graph.html#barabasi-albert-graph) with 100 nodes and attach 3 edges to  a new node in the graph (`m=3`).
- Plot the [degree_centrality](https://networkx.org/documentation/latest/reference/algorithms/generated/networkx.algorithms.bipartite.centrality.degree_centrality.html) distribution (a histogram of the degree histogram).
- Infer the changes in the plots, why does the degree centrality distribution change between these 2 random graph generators Create a markdown cell in the jupyter notebook and write what you can infer from the plots. 

Create a pull request against this repository and add the file `2023-round-1/<your-github-username>/nx_notebook.ipynb` with the notebook which performs all the operations above.

**Comment by AniketARS** [comment]
Hello @MridulS,
Is this task also relevant for Outreachy Contribution Period round 2 (WInter)?

**Comment by Naman-Priyadarshi** [comment]
I have completed this task there is no current directory named `2023-round-2`, should I wait for you to create a directory for the following?

**Comment by MridulS** [comment]
It should be `2023-round-1`, I need to fix the typo. Thanks for the catch!

**Comment by devotuoma** [comment]
Created an exploratory notebook #8  please review my contribution @ MridulS
